import json
import os
import time
from datetime import datetime, timezone
from typing import Optional

from fastapi import FastAPI
from pydantic import BaseModel
from google import genai
from google.genai import types



GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise ValueError(
        "GEMINI_API_KEY environment variable not set. "
        "Get your API key from: https://aistudio.google.com/apikey"
    )

GEMINI_MODEL = os.getenv("MATCHER_GEMINI_MODEL", "gemini-2.5-flash")


LOG_DIR = os.getenv("MATCHER_LOG_DIR", ".")
LOG_FILE = os.path.join(LOG_DIR, "gemini_matcher_log.jsonl")

client = genai.Client(api_key=GEMINI_API_KEY)

print(f"[INIT] Semantic Matcher v4 (Gemini LLM)")
print(f"[INIT] Model: {GEMINI_MODEL}")
print(f"[INIT] Log:   {LOG_FILE}")



def log_call(entry: dict) -> None:
    """Append one JSON line to the log file."""
    try:
        os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    except Exception as e:
        print(f"[WARN] Failed to write log: {e}")




MATCH_SYSTEM_PROMPT = """\
You are a precise judge evaluating whether two bug descriptions refer to the SAME \
underlying visual glitch in a video game clip.

You will receive:
- PREDICTED: A bug description generated by a vision model.
- GROUND_TRUTH_1 and optionally GROUND_TRUTH_2: Human-written reference descriptions of the actual bug.

Rules:
1. MATCH if the predicted description describes the SAME core bug event as \
either ground truth — even if wording differs (e.g., "gate" vs "fence", \
"launched into air" vs "flies into sky").
2. NO_MATCH if the predicted description describes a DIFFERENT bug, a different \
object, or a different mechanism — even if both mention the same scene.
3. Focus on WHAT went wrong and TO WHAT, not on exact vocabulary.
4. Partial overlap (same object, different bug) is NO_MATCH.
5. Describing the same bug from a different angle or with different detail level is still MATCH.

Respond with ONLY this JSON (no extra text):
{
  "match": true or false,
  "reasoning": "one sentence explaining why"
}\
"""


def build_match_prompt(
    pred: str,
    gt1: Optional[str],
    gt2: Optional[str],
) -> str:
    """Build the user prompt for the match judgment."""
    gt1 = (gt1 or "").strip()
    gt2 = (gt2 or "").strip()

    parts = [f"PREDICTED: {pred}"]

    if not gt1 and not gt2:
        parts.append("No glitch in this video")
    else:
        if gt1:
            parts.append(f"GROUND_TRUTH_1: {gt1}")
        if gt2:
            parts.append(f"GROUND_TRUTH_2: {gt2}")

    return "\n".join(parts)




def call_gemini_match(
    pred: str,
    gt1: Optional[str],
    gt2: Optional[str],
    max_retries: int = 3,
) -> dict:
    
    user_prompt = build_match_prompt(pred, gt1, gt2)

    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=[
                    types.Content(
                        role="user",
                        parts=[types.Part(text=user_prompt)],
                    ),
                ],
                config=types.GenerateContentConfig(
                    temperature=0.0,
                    system_instruction=MATCH_SYSTEM_PROMPT,
                ),
            )

            raw_text = (response.text or "").strip()
            text = raw_text

            # Handle markdown code fences
            if text.startswith("```"):
                text = text.split("\n", 1)[-1].rsplit("```", 1)[0].strip()

            try:
                start = text.index("{")
                end = text.rindex("}") + 1
                obj = json.loads(text[start:end])
            except (ValueError, json.JSONDecodeError):
                print(
                    f"[WARN] Could not parse Gemini response "
                    f"(attempt {attempt + 1}): {text[:200]}"
                )
                if attempt < max_retries - 1:
                    time.sleep(1)
                    continue
                return {
                    "match": False,
                    "reasoning": f"parse_error: {text[:100]}",
                    "raw_response": raw_text,
                    "system_prompt": MATCH_SYSTEM_PROMPT,
                    "user_prompt": user_prompt,
                }

            return {
                "match": bool(obj.get("match", False)),
                "reasoning": str(obj.get("reasoning", "")),
                "raw_response": raw_text,
                "system_prompt": MATCH_SYSTEM_PROMPT,
                "user_prompt": user_prompt,
            }

        except Exception as e:
            print(
                f"[ERROR] Gemini call failed (attempt {attempt + 1}): {e}"
            )
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)
                continue
            return {
                "match": False,
                "reasoning": f"api_error: {str(e)[:100]}",
                "raw_response": "",
                "system_prompt": MATCH_SYSTEM_PROMPT,
                "user_prompt": user_prompt,
            }

    return {
        "match": False,
        "reasoning": "max_retries_exceeded",
        "raw_response": "",
        "system_prompt": MATCH_SYSTEM_PROMPT,
        "user_prompt": user_prompt,
    }



class SemanticMatchRequest(BaseModel):
    predicted_description: str
    ground_truth_1: Optional[str] = None
    ground_truth_2: Optional[str] = None


class SemanticMatchResponse(BaseModel):
    match: bool
    confidence: Optional[str] = None
    reasoning: Optional[str] = None
    backend: Optional[str] = None


app = FastAPI(title="Semantic Matcher v4 (Gemini LLM)")


@app.post("/match", response_model=SemanticMatchResponse)
def semantic_match(req: SemanticMatchRequest) -> SemanticMatchResponse:
    if not req.predicted_description:
        return SemanticMatchResponse(
            match=False, reasoning="empty prediction", backend="gemini"
        )

    if not req.ground_truth_1 and not req.ground_truth_2:
        return SemanticMatchResponse(
            match=False, reasoning="no ground truth", backend="gemini"
        )

    result = call_gemini_match(
        req.predicted_description,
        req.ground_truth_1,
        req.ground_truth_2,
    )


    log_call({
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "model": GEMINI_MODEL,
        "system_prompt": result["system_prompt"],
        "user_prompt": result["user_prompt"],
        "predicted_description": req.predicted_description,
        "ground_truth_1": req.ground_truth_1,
        "ground_truth_2": req.ground_truth_2,
        "raw_response": result["raw_response"],
        "match": result["match"],
        "reasoning": result["reasoning"],
    })

    print(
        f"[GEMINI] {'MATCH' if result['match'] else 'NO MATCH'} | "
        f"pred='{req.predicted_description[:60]}' | "
        f"reason='{result['reasoning'][:80]}'"
    )

    return SemanticMatchResponse(
        match=result["match"],
        confidence=None,
        reasoning=result["reasoning"],
        backend="gemini",
    )


@app.get("/health")
def health():
    return {
        "status": "healthy",
        "version": "v4-gemini",
        "backend": "gemini",
        "model": GEMINI_MODEL,
        "threshold": "n/a (LLM judge)",
        "device": "api",
        "log_file": LOG_FILE,
    }


@app.get("/")
def root():
    return {
        "service": "Semantic Matcher v4 (Gemini LLM)",
        "model": GEMINI_MODEL,
        "log_file": LOG_FILE,
    }


if __name__ == "__main__":
    import uvicorn

    port = int(os.getenv("PORT", "8002"))
    uvicorn.run(app, host="0.0.0.0", port=port)